on:
  pull_request:
    types: [opened]

jobs:
  generate-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install node-fetch
      - name: Generate comments
        run: |
          node scripts/generate_comment.js
